prompt_format: 
  - |
    **Previous Failed Attempt:**
    ```lean4
    {}
    ```

    **Error Messages:**
    {}

    **Current Task:**
    Complete the following Lean 4 code:

    ```lean4
    {}
    ```

    Before producing the Lean 4 code to formally prove the given theorem, provide a detailed proof plan outlining the main proof steps and strategies.
    The plan should highlight key ideas, intermediate lemmas, and proof structures that will guide the construction of the final formal proof.
    Please learn from the previous failed attempt and error messages to avoid similar mistakes.
